apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    app.kubernetes.io/name: lovelog
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  POSTGRES_USER: {{ "postgres" | b64enc }}
  POSTGRES_PASSWORD: {{ "postgres" | b64enc }}
  POSTGRES_DB: {{ "lovelog" | b64enc }}
  SECRET_KEY: {{ "chave-muito-secreta-1234" | b64enc }}
