{{- if .Values.volumes }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
  labels:
    app.kubernetes.io/name: lovelog
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volumes.static.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  labels:
    app.kubernetes.io/name: lovelog
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volumes.media.size }}
{{- end }}
