replicaCount: 1

image:
  repository: backend
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

env:
  # Database configuration
  DB_HOST: "lovelog-postgres"
  DB_PORT: "5432"
  
  # Django configuration
  DEBUG: "False"
  ALLOWED_HOSTS: "k8s.local,localhost,127.0.0.1"
  CORS_ALLOWED_ORIGINS: "http://k8s.local,http://localhost:3000"
  CORS_ALLOW_ALL_ORIGINS: "True"
  CSRF_TRUSTED_ORIGINS: "http://k8s.local,http://localhost:3000"
  MEDIA_URL: "/media/"

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi
