# Generated by Django 5.2 on 2025-06-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Board', 'verbose_name_plural': 'Boards'},
        ),
        migrations.AddField(
            model_name='board',
            name='background_color',
            field=models.CharField(default='#ffffff', help_text='Cor de fundo em hexadecimal', max_length=7),
        ),
        migrations.AddField(
            model_name='board',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Board privado (visível apenas para o casal)'),
        ),
    ]
