# Generated by Django 5.2 on 2025-06-26 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_options_board_background_color_and_more'),
        ('couples', '0002_remove_couple_password_couple_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, help_text='Último usuário que editou o board', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_boards', to='couples.user'),
        ),
        migrations.AddField(
            model_name='board',
            name='title',
            field=models.CharField(blank=True, help_text='Título do board', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='Conteúdo do board em formato JSON', null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='couple',
            field=models.OneToOneField(help_text='Casal proprietário do board', on_delete=django.db.models.deletion.CASCADE, related_name='board', to='couples.couple'),
        ),
    ]
