apiVersion: v2
name: lovelog-chart
description: A Helm chart for LoveLog application - A romantic photo and todo list app
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgres
    version: 0.1.0
    repository: "file://charts/postgres"
  - name: backend
    version: 0.1.0
    repository: "file://charts/backend"
  - name: frontend
    version: 0.1.0
    repository: "file://charts/frontend"
  - name: nginx
    version: 0.1.0
    repository: "file://charts/nginx"
