# Generated by Django 5.2 on 2025-06-26 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couples', '0002_remove_couple_password_couple_created_at_and_more'),
        ('lists', '0002_rename_status_item_completed_alter_item_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['completed', '-priority', 'created_at'], 'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['name'], 'verbose_name': 'Lista', 'verbose_name_plural': 'Listas'},
        ),
        migrations.AddField(
            model_name='item',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Usuário responsável pelo item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_items', to='couples.user'),
        ),
        migrations.AddField(
            model_name='item',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Data/hora de conclusão', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou o item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to='couples.user'),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição detalhada do item', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Data limite para conclusão', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', help_text='Prioridade do item', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='list',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou a lista', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lists', to='couples.user'),
        ),
        migrations.AddField(
            model_name='list',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição da lista', null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Lista arquivada'),
        ),
        migrations.AddField(
            model_name='list',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', help_text='Prioridade da lista', max_length=10),
        ),
        migrations.AddField(
            model_name='list',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='completed',
            field=models.BooleanField(default=False, help_text='Item completado'),
        ),
        migrations.AlterField(
            model_name='item',
            name='list',
            field=models.ForeignKey(help_text='Lista à qual este item pertence', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lists.list', verbose_name='Lista'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='Nome do item', max_length=255),
        ),
        migrations.AlterField(
            model_name='list',
            name='couple',
            field=models.ForeignKey(help_text='Casal proprietário da lista', on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='couples.couple'),
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(help_text='Nome da lista', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='list',
            unique_together={('couple', 'name')},
        ),
    ]
