replicaCount: 1

image:
  repository: frontend
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

env:
  apiUrl: "/api"

livenessProbe:
  enabled: true
  path: /
  initialDelaySeconds: 30
  periodSeconds: 30

readinessProbe:
  enabled: true
  path: /
  initialDelaySeconds: 5
  periodSeconds: 10

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
